name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: update latest n2n version
      run: git clone https://github.com/ntop/n2n.git && \
           cd n2n && \
           export N2N_VERSION=$(git tag -l "3.*" --sort=-v:refname|head -n1) && \
           cd .. && \
           sed -i "s/--branch 3\.[0-9\.]*/--branch $N2N_VERSION/" ./n2n_v3_{edge,supernode}/Dockerfile && \
           cat ./n2n_v3_{edge,supernode}/Dockerfile
    - name: Build supernode docker and push
      uses: docker/build-push-action@v3
      with:
          context: ./n2n_v3_supernode
          push: true
          tags: dorasan/n2n_v3_supernode:latest
    - name: Build edge docker and push
      uses: docker/build-push-action@v3
      with:
          context: ./n2n_v3_edge
          push: true
          tags: dorasan/n2n_v3_edge:latest
      
