name: n2n_v3_edge Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docker and push
      uses: docker/build-push-action@v3
      with:
          context: ./n2n_v3_edge
          push: true
          tags: dorasan/n2n_v3_edge:latest
      
